### ISSUE TITLE
click the button send to controlnet，noting happen？

### ISSUE THREAD

**Issue by ywdong** [jexom/sd-webui-depth-lib#10]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1457889/223027274-ec73485f-32dd-40c8-bfee-335ae42be526.png)

**Environment**
Put x in the brackets to select
- [x] Local desktop
- [ ] Colab

**To Reproduce**

**Expected behavior**

**Comment by jexom** [comment]
Anything in the logs? Local or colab (asking because you completely igored the template)

**Comment by jexom** [comment]
Closing due to lack of response
