### ISSUE TITLE
'Send to ControlNet' does not work.

### ISSUE THREAD

**Issue by Westernnero** [jexom/sd-webui-depth-lib#21]
**Describe the bug**

'Send to ControlNet' does not work. After clicking, nothing happened.
I have no idea what's the problem here. Everything has been updated when I post this.

It's weird because the very same button in OpenPose Editor does not work, too.

The following pic is what it is like after clicking the button. I did not change anything or choose any models yet.

![image](https://user-images.githubusercontent.com/40510735/228233968-819fb47d-564b-4801-ae87-a08d0bd6146c.png)

my gradio version is 3.23.0. I tried 'pip install gradio==3.16.2' but everytime I run 'webui-user.bat' it keeps showing 3.23.0. Is this the reason? Sorry I am not sure what to do to stop it upgrade.
'UPDATED': I tried to modify the 'requirement.txt' and changed gradio==3.23 to 3.16.2 but ran into errors and the SD webui just cannot be launched. I dont know if information can help you but it seems that I really cannot go with gradio==3.16.2. I am so sorry...

Any further details required about my system please let me know.

**Environment**
Put x in the brackets to select
- [x] Local desktop
- [ ] Colab

**To Reproduce**
0. Launch sd-webui.
1. Go to 'Depth Library', adjust the hand shape then click 'add'.
2. Click on 'Send to ControlNet'. Nothing happened.
3.  No response in CMD, too.
![image](https://user-images.githubusercontent.com/40510735/228234442-7e17c58d-d183-4518-ac51-0d9fae8d5127.png)

**Expected behavior**

**Comment by jexom** [comment]
Yeah I havent updated webui yet because of the breaking changes done to the main.

**Comment by Westernnero** [comment]
OK thanks. Though not sure if gradio version has caused that, I'll take it.
Thank you for your response and all the works jexom!

**Comment by AdAstra-93** [comment]
any updates on this? seems like it's been a year since, and the problem still persists
