### ISSUE TITLE
Are the sample depth maps working as they should?

### ISSUE THREAD

**Issue by jav12z** [jexom/sd-webui-depth-lib#6]
After many tests I have a strange feeling about the depth maps given as samples, it's like SD is not understanding them as well as it should.

I've tried with other custom depth maps, even with less resolution and more complex poses, and the results have been better. Maybe I'm wrong, but I've this feeling.

Example maintaining the same config for both renders and same seed. 
![ejemplo](https://user-images.githubusercontent.com/110166549/222953876-5bf4092d-0e82-4476-821b-517c8d2caabe.jpg)

**Comment by TomiTom1234** [comment]
I discovered the best way to get a perfect result.
After you create an image, and after you add the proper hand over the background image in "depth library", send it to ControlNET (of course same seed), leave the "weight" at 1, increase the "guidance start" to 0.3, leave "guess" unchecked.. (sure you have to chose "depth" model, and enable ControlNET)
The result I got is perfect (almost identical with hand correction)  :
![00356-3977979584-a man wearing___](https://user-images.githubusercontent.com/125768071/222958907-9a9dceec-3e61-42ac-8773-adba56eb93c0.png)

![00252-3977979584-a man wearing a suit, waving with his hand](https://user-images.githubusercontent.com/125768071/222958935-389c8a8e-0ea7-435e-8391-001e05da075b.png)

**Comment by DocShotgun** [comment]
I've also had success inpainting with the depth maps, although for that I leave the guidance start at 0.

**Comment by jexom** [comment]
Use a lower weight. These were rendered up close in blender, so they're really close to the camera. Besides as @TomiTom1234 said, without the full body depth map these are better used for fixing good seeds, rather than generating from scratch.

**Comment by jexom** [comment]
Closing as a non extension related issue
