### ISSUE TITLE
Error: NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by demirklvc** [jexom/sd-webui-depth-lib#7]
NameError: name 'file' is not defined.

please help.

**Comment by jexom** [comment]
That alone doesn't tell me anything. There's a reason there's a template.
Possible duplicate of #2

**Comment by jexom** [comment]
Try updating and using it now, switched to usinf the method provided in webui to get the base directory of the extension

**Comment by jexom** [comment]
Assuming duplicate of #2
