### ISSUE TITLE
Add opacity and background brightness settings 

### ISSUE THREAD

**Issue by jexom** [jexom/sd-webui-depth-lib#8]
**Is your feature request related to a problem? Please describe.**
As of now the base depth of the background is considered infinitely far and the depth maps are way too close to the "camera"

**Describe the solution you'd like**
Choosing brightness for the background would allow setting the base depth for the image. While changing the depth map opacity would allow it to be positioned in the depth dimension.

**Comment by ostap667inbox** [comment]
...and 'remove background image' feature? (opacity=0)

**Comment by jexom** [comment]
> ...and 'remove background image' feature? (opacity=0)

The background isn't exported when saving or sending to control net. And having a depth map with a transparent background serves no purpose
